services:
  redis-web:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  web:
    build: ./web
    container_name: web-app
    ports:
      - "8000:8000"
    depends_on:
      - redis-web
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

